spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fictionalbank
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
springdoc:
  swagger-ui:
    url: /openapi.yaml
jwt:
  secret: uQw8vQ1pQ2t6bXJ5dGZzZ2hqa2xtbm9wcXJzdHV2d3h5eg== #base64 valid secret
  expiration: 86400000 # 1 day in milliseconds